//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ReLoop.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ReLoop.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap porta_aperta {
            get {
                object obj = ResourceManager.GetObject("porta_aperta", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap porta_boss {
            get {
                object obj = ResourceManager.GetObject("porta_boss", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap porta_chiusa {
            get {
                object obj = ResourceManager.GetObject("porta_chiusa", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ringo, un ragazzo di 16 anni si sveglia in un corridoio pieno di porte,
        ///il ragazzo confuso e smarrito decide di entrare in una delle porte..
        /// </summary>
        internal static string story_0 {
            get {
                return ResourceManager.GetString("story_0", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ringo capisce che qualcuno o qualcosa lo sta intrappolando in quello
        ///strano corridoio e che ogni volta che controlla una stanza di esso,
        ///si ritroverà sempre nel corridoio venendo così intrappolato in un loop..
        /// </summary>
        internal static string story_1 {
            get {
                return ResourceManager.GetString("story_1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ringo improssivamente comincia a ricordare
        ///delle memorie che non combaciano con quelle che già aveva,
        ///confuso decide di continuare..
        /// </summary>
        internal static string story_2 {
            get {
                return ResourceManager.GetString("story_2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ringo riacquista tutti i suoi ricordi e viene a conoscenza dell&apos;esistenza di
        ///un demone che divorando le memorie del ragazzo le stava alterando  e accidentalmente
        ///lo trasporta nel suo reame, adesso Ringo per tornare alla normalità dovrà sconfiggerlo
        ///recandosi nella stanza nel mezzo del corridoio..
        /// </summary>
        internal static string story_3 {
            get {
                return ResourceManager.GetString("story_3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap tesoro {
            get {
                object obj = ResourceManager.GetObject("tesoro", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
